# Data frame contenant les noms, identifiants et handle des collections de la nav-bar du store
navbar <- data.frame(title = c("Fruits & Légumes",
                                "Crèmerie",
                                "Viandes",
                                "Poissonnerie",
                                "Traiteur",
                                "Boulangerie / Pâtisserie",
                                "Epicerie Sucrée",
                                "Epicerie Salée",
                                "Boissons",
                                "Cave",
                                "Hygiène et Entretien",
                                "Fleurs",
                                "Bébés & Enfants"),
                     handle = c("fruits-legumes",
                                 "produits-laitiers",
                                 "viandes",
                                 "poissonnerie",
                                 "traiteur",
                                 "patisserie-boulangerie",
                                 "epicerie-sucree",
                                 "epicerie-salee",
                                 "boissons",
                                 "cave",
                                 "hygiene-et-entretien",
                                 "fleurs",
                                 "bebes-enfants"),
                     id = c(399234954,
                             399241162,
                             28828333,
                             399239882,
                             13046186013,
                             399236298,
                             435241226,
                             435243530,
                             417670538,
                             416960842,
                             448607754,
                             33088274521,
                             448511946))
