# Data frame contenant les noms, identifiants et taux de taxes des tax overrides
tax_overrides <- data.frame(title = c("cave",
                                      "hygiene-et-entretien",
                                      "fleurs",
                                      "chocolat-au-lait",
                                      "coffrets-alcool",
                                      "frais-livraison"),
                            id = c(416960842,
                                   448607754,
                                   33088274521,
                                   399320330,
                                   12121309213,
                                   33005895769),
                            tax_rate = c(0.2,
                                         0.2,
                                         0.1,
                                         0.2,
                                         0.2,
                                         0.2))